spring.application.name=backend


spring.datasource.username=ADMIN
spring.datasource.password=NextWordBD542


spring.datasource.url=jdbc:oracle:thin:@nextwordbd_high?TNS_ADMIN=C:/Users/jairv/Downloads/Wallet_NextWordBD/Wallet_NextWordBD
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.idle-timeout=300000

application.security.jwt.secret-key=McvbIKwPaVjhmKBwFUdHDXzvfWeAZgaJ8XJr6cBsvNkPI9VUvAWw7GzFMV6ZhHsI
application.security.jwt.expiration=86400000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=20243ds096@utez.edu.mx

spring.mail.password=otwttycuinfbcmhx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
